# Generated by Django 5.0.14 on 2026-03-11 11:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit être au format international. Ex: +243812345678', regex='^\\+?[1-9]\\d{7,14}$')])),
                ('code_hash', models.CharField(max_length=64)),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Code OTP',
                'verbose_name_plural': 'Codes OTP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit être au format international. Ex: +243812345678', regex='^\\+?[1-9]\\d{7,14}$')], verbose_name='Numéro de téléphone')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('role', models.CharField(choices=[('passenger', 'Passager'), ('driver', 'Chauffeur'), ('admin', 'Administrateur')], default='passenger', max_length=10, verbose_name='Rôle')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', verbose_name='Photo de profil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='Téléphone vérifié')),
                ('fcm_token', models.CharField(blank=True, default='', max_length=255, verbose_name='Token FCM')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_make', models.CharField(max_length=50, verbose_name='Marque véhicule')),
                ('vehicle_model', models.CharField(max_length=50, verbose_name='Modèle véhicule')),
                ('vehicle_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Année du véhicule')),
                ('vehicle_color', models.CharField(max_length=30, verbose_name='Couleur véhicule')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name="Plaque d'immatriculation")),
                ('drivers_license_photo', models.ImageField(upload_to='documents/licenses/', verbose_name='Photo permis de conduire')),
                ('vehicle_registration_photo', models.ImageField(upload_to='documents/registrations/', verbose_name='Photo carte grise')),
                ('vehicle_photo', models.ImageField(upload_to='documents/vehicles/', verbose_name='Photo du véhicule')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('suspended', 'Suspendu')], default='pending', max_length=10, verbose_name='Statut du compte')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='Raison du rejet')),
                ('is_online', models.BooleanField(default=False, verbose_name='En ligne')),
                ('is_on_ride', models.BooleanField(default=False, verbose_name='En course')),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('last_location_update', models.DateTimeField(blank=True, null=True, verbose_name='Dernière mise à jour position')),
                ('rating_average', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='Note moyenne')),
                ('total_rides', models.PositiveIntegerField(default=0, verbose_name='Courses totales')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Revenus totaux')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil chauffeur',
                'verbose_name_plural': 'Profils chauffeurs',
            },
        ),
    ]
