# Generated by Django 5.0.14 on 2026-03-11 11:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_address', models.CharField(max_length=300, verbose_name='Adresse de départ')),
                ('pickup_latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitude départ')),
                ('pickup_longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitude départ')),
                ('destination_address', models.CharField(max_length=300, verbose_name="Adresse d'arrivée")),
                ('destination_latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitude arrivée')),
                ('destination_longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitude arrivée')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Distance (km)')),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée estimée (min)')),
                ('estimated_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix estimé')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix final')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Commission')),
                ('driver_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Revenu chauffeur')),
                ('status', models.CharField(choices=[('requested', 'Demandée'), ('accepted', 'Acceptée'), ('driver_arriving', 'Chauffeur en route'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled_passenger', 'Annulée par passager'), ('cancelled_driver', 'Annulée par chauffeur')], default='requested', max_length=25, verbose_name='Statut')),
                ('cancellation_reason', models.TextField(blank=True, default='', verbose_name="Raison d'annulation")),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Réduction')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Demandé le')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Accepté le')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Démarré le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Annulé le')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides_as_driver', to=settings.AUTH_USER_MODEL, verbose_name='Chauffeur')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_passenger', to=settings.AUTH_USER_MODEL, verbose_name='Passager')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='promotions.promocode')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='RideLocationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to='rides.ride')),
            ],
            options={
                'verbose_name': 'Position GPS',
                'verbose_name_plural': 'Positions GPS',
                'ordering': ['recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='SOSAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Résolue')], default='active', max_length=10)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to='rides.ride')),
                ('triggered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerte SOS',
                'verbose_name_plural': 'Alertes SOS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status'], name='rides_ride_status_b1560e_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['passenger', '-requested_at'], name='rides_ride_passeng_b6e2e4_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['driver', '-requested_at'], name='rides_ride_driver__e9c19e_idx'),
        ),
    ]
