# Generated by Django 5.0.6 on 2026-03-26 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, help_text='Currently assigned driver (pending acceptance)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Chauffeur assigné'),
        ),
        migrations.AddField(
            model_name='ride',
            name='assignment_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration assignation'),
        ),
        migrations.AddField(
            model_name='ride',
            name='declined_driver_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='Chauffeurs ayant décliné'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('requested', 'Demandée'), ('accepted', 'Acceptée'), ('driver_arriving', 'Chauffeur en route'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled_passenger', 'Annulée par passager'), ('cancelled_driver', 'Annulée par chauffeur'), ('no_driver', 'Aucun chauffeur disponible')], default='requested', max_length=25, verbose_name='Statut'),
        ),
    ]
