# Generated by Django 5.0.6 on 2026-03-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_ride_assigned_driver_ride_assignment_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('requested', 'Demandée'), ('accepted', 'Acceptée'), ('driver_arriving', 'Chauffeur en route'), ('driver_arrived', 'Chauffeur arrivé'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled_passenger', 'Annulée par passager'), ('cancelled_driver', 'Annulée par chauffeur'), ('no_driver', 'Aucun chauffeur disponible')], default='requested', max_length=25, verbose_name='Statut'),
        ),
    ]
