# Generated by Django 5.0.6 on 2026-03-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='acceptance_rate',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Percentage of ride requests accepted (0-100)', max_digits=5, verbose_name="Taux d'acceptation"),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='cancellation_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of rides cancelled by driver (0-100)', max_digits=5, verbose_name="Taux d'annulation"),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='last_ride_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière course'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='rides_today',
            field=models.PositiveIntegerField(default=0, verbose_name="Courses aujourd'hui"),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='rides_today_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date compteur journalier'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='total_accepted',
            field=models.PositiveIntegerField(default=0, verbose_name='Courses acceptées'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='total_cancelled',
            field=models.PositiveIntegerField(default=0, verbose_name='Courses annulées'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='total_declined',
            field=models.PositiveIntegerField(default=0, verbose_name='Courses déclinées'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='vehicle_category',
            field=models.CharField(choices=[('economy', 'Économie'), ('comfort', 'Confort'), ('van', 'Van')], default='economy', max_length=10, verbose_name='Catégorie véhicule'),
        ),
    ]
