# Generated by Django 5.0.14 on 2026-03-11 11:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('currency', models.CharField(default='CDF', max_length=5, verbose_name='Devise')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué')], default='pending', max_length=10)),
                ('rides_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de courses')),
                ('period_start', models.DateField(verbose_name='Début période')),
                ('period_end', models.DateField(verbose_name='Fin période')),
                ('provider_transaction_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versement chauffeur',
                'verbose_name_plural': 'Versements chauffeurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('currency', models.CharField(default='CDF', max_length=5, verbose_name='Devise')),
                ('method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('cash', 'Espèces'), ('wallet', 'Portefeuille')], default='mobile_money', max_length=15, verbose_name='Moyen de paiement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=12, verbose_name='Statut')),
                ('provider_transaction_id', models.CharField(blank=True, default='', max_length=100, verbose_name='ID transaction fournisseur')),
                ('provider_response', models.JSONField(blank=True, null=True, verbose_name='Réponse fournisseur')),
                ('phone_number', models.CharField(blank=True, default='', max_length=16, verbose_name='Numéro Mobile Money')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
    ]
