# Generated by Django 5.0.6 on 2026-03-26 01:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        ('rides', '0002_ride_assigned_driver_ride_assignment_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverpayout',
            name='period_end',
        ),
        migrations.RemoveField(
            model_name='driverpayout',
            name='period_start',
        ),
        migrations.RemoveField(
            model_name='driverpayout',
            name='rides_count',
        ),
        migrations.AddField(
            model_name='driverpayout',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Numéro retrait'),
        ),
        migrations.AddField(
            model_name='driverpayout',
            name='provider_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverpayout',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Complété'), ('failed', 'Échoué')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('mobile_money', 'Mobile Money'), ('cash', 'Espèces'), ('wallet', 'Portefeuille')], default='wallet', max_length=15, verbose_name='Moyen de paiement'),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Solde disponible')),
                ('held_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount pre-authorized for an ongoing ride', max_digits=12, verbose_name='Montant bloqué')),
                ('currency', models.CharField(default='CDF', max_length=5, verbose_name='Devise')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('blocked', 'Bloqué')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portefeuille',
                'verbose_name_plural': 'Portefeuilles',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_type', models.CharField(choices=[('deposit', 'Dépôt'), ('ride_payment', 'Paiement course'), ('ride_hold', 'Pré-autorisation'), ('hold_release', 'Libération blocage'), ('refund', 'Remboursement'), ('commission', 'Commission'), ('ride_earning', 'Revenu course'), ('payout', 'Retrait Mobile Money')], max_length=15, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Solde après')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué')], default='completed', max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=100, verbose_name='Réf. fournisseur')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='rides.ride')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.wallet')),
            ],
            options={
                'verbose_name': 'Transaction wallet',
                'verbose_name_plural': 'Transactions wallet',
                'ordering': ['-created_at'],
            },
        ),
    ]
