# Generated by Django 5.0.14 on 2026-03-11 11:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('body', models.TextField(verbose_name='Contenu')),
                ('channel', models.CharField(choices=[('push', 'Push'), ('sms', 'SMS'), ('in_app', 'In-App')], default='push', max_length=10)),
                ('category', models.CharField(choices=[('ride', 'Course'), ('payment', 'Paiement'), ('promo', 'Promotion'), ('system', 'Système'), ('sos', 'SOS')], default='system', max_length=10)),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Données supplémentaires')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Envoyé le')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['recipient', '-sent_at'], name='notificatio_recipie_b23b38_idx')],
            },
        ),
    ]
